"""taking out linked members

Revision ID: 0462785ddd1f
Revises: e200e301acdc
Create Date: 2023-09-19 22:15:45.402879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0462785ddd1f'
down_revision = 'e200e301acdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('families')
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prayer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_prayers_member_id_members', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_prayers_prayer_id_prayers'), 'prayers', ['prayer_id'], ['id'])
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_prayers_prayer_id_prayers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_prayers_member_id_members', 'members', ['member_id'], ['id'])
        batch_op.drop_column('prayer_id')

    op.create_table('families',
    sa.Column('family_id', sa.INTEGER(), nullable=False),
    sa.Column('families_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['families_id'], ['members.id'], name='fk_families_families_id_members'),
    sa.ForeignKeyConstraint(['family_id'], ['members.id'], name='fk_families_family_id_members'),
    sa.PrimaryKeyConstraint('family_id', 'families_id')
    )
    # ### end Alembic commands ###
