"""taking out linked members

Revision ID: 1382604545d5
Revises: 0462785ddd1f
Create Date: 2023-09-19 22:16:59.184317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1382604545d5'
down_revision = '0462785ddd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('families_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['families_id'], ['members.id'], name=op.f('fk_families_families_id_members')),
    sa.ForeignKeyConstraint(['family_id'], ['members.id'], name=op.f('fk_families_family_id_members')),
    sa.PrimaryKeyConstraint('family_id', 'families_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('families')
    # ### end Alembic commands ###
