"""name vs first & last name

Revision ID: 285f2f726f82
Revises: e1231b645da7
Create Date: 2023-09-20 21:52:15.149164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285f2f726f82'
down_revision = 'e1231b645da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
