"""taking out linked members

Revision ID: 5867adcf9a44
Revises: 1382604545d5
Create Date: 2023-09-19 22:26:51.059724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5867adcf9a44'
down_revision = '1382604545d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prayers_prayer_id_prayers', type_='foreignkey')
        batch_op.drop_column('prayer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prayer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_prayers_prayer_id_prayers', 'prayers', ['prayer_id'], ['id'])

    # ### end Alembic commands ###
