"""vihn method

Revision ID: e1231b645da7
Revises: 
Create Date: 2023-09-20 21:38:45.702100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1231b645da7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('families',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('families_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['families_id'], ['members.id'], name=op.f('fk_families_families_id_members')),
    sa.ForeignKeyConstraint(['family_id'], ['members.id'], name=op.f('fk_families_family_id_members')),
    sa.PrimaryKeyConstraint('family_id', 'families_id')
    )
    op.create_table('mpinstances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('prayer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_mpinstances_member_id_members')),
    sa.ForeignKeyConstraint(['prayer_id'], ['prayers.id'], name=op.f('fk_mpinstances_prayer_id_prayers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpinstances')
    op.drop_table('families')
    op.drop_table('users')
    op.drop_table('prayers')
    op.drop_table('members')
    # ### end Alembic commands ###
