"""adding followers ?

Revision ID: e200e301acdc
Revises: 2016bf82e502
Create Date: 2023-09-12 20:33:24.477117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e200e301acdc'
down_revision = '2016bf82e502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('families_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['families_id'], ['members.id'], name=op.f('fk_families_families_id_members')),
    sa.ForeignKeyConstraint(['family_id'], ['members.id'], name=op.f('fk_families_family_id_members')),
    sa.PrimaryKeyConstraint('family_id', 'families_id')
    )
    op.create_table('mpinstances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('prayer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_mpinstances_member_id_members')),
    sa.ForeignKeyConstraint(['prayer_id'], ['prayers.id'], name=op.f('fk_mpinstances_prayer_id_prayers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpinstances')
    op.drop_table('families')
    # ### end Alembic commands ###
